name: Respository Dispacth manual
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        description: 'Something to send to the other workflow'
        required: true
        default: 'Foo'
        
jobs:
  dispatcher:
    name: 'Dispatcher'
    runs-on: ubuntu-latest
    steps:
     - run: | 
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}"\
        -H  Content-Type: `application/json"
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/lblasnar/testWorkflowDispatch/dispatches \
        --data-raw '{ "event_type": "rep_dispatch", "client_payload": {"test": "${{ inputs.test}}"}}'
