name: Respository Dispacth manual
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        description: 'Something to send to the other workflow'
        required: true
        default: 'Foo'
        
jobs:
  dispatcher:
    name: 'Dispatcher'
    runs-on: ubuntu-latest
    steps:
     - run: | 
        curl https://api.github.com/repos/lblasnar/testWorkflowDispatch/dispatches \
        --request POST \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Content-Type: application/javascript' \
        -H 'Authorization: Bearer ${{ secrets.PAT_TOKEN }}' \
        --data-raw '{ "event_type": "rep_dispatch", "client_payload": {"test": "${{ inputs.test}}"}}'
        
