name: Workflow Dispacth manual
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  
permissions:
  contents: write
  packages: write
  checks: write
  
jobs:
  dispatcher:
    name: 'Dispatcher'
    runs-on: ubuntu-latest
    steps:
     - uses: actions/github-script@v6
       with:
         github-token: ${{ secrets.PAT_TOKEN }}
         script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'lblasnar',
              repo: 'testWorkflowDispatch',
              workflow_id: 'test.yml',
              ref: 'main'
            })
