name: Workflow Dispacth manual
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  
permissions:
  contents: write
  packages: write
  checks: write
  
jobs:
  dispatcher:
    name: 'Dispatcher'
    runs-on: ubuntu-latest
    steps:
     - name: 'Dispatch'
       run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTIONS_RUNNER_DEBUG }}" https://api.github.com/repos/lblasnar/testWorkflowDispatch/actions/workflows/test.yml/dispatches -d '{"ref":"main"}'
