name: Workflow Dispacth manual
defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      aInput:
        type: string
        
jobs:
  dispatcher:
    name: "Dispatcher"
    runs-on: ubuntu-latest
    steps:
      - name: Dispatcher
        run: |
          echo "Running dispatcher"
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/lblas/workflowDispatch/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'
