name: Workflow Dispacth manual
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  
permissions:
  contents: write
  packages: write
  checks: write
  
jobs:
  dispatcher:
    name: 'Dispatcher'
    runs-on: ubuntu-latest
    steps:
     - name: 'Dispatch'
       run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/lblasnar/testWorkflowDispatch/actions/workflows/test.yml/dispatches -d '{"ref":"main"}'
